// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinalDesarrollo.Connection;

namespace ProyectoFinalDesarrollo.Migrations
{
    [DbContext(typeof(conn))]
    [Migration("20201015064533_migracion_makepeace")]
    partial class migracion_makepeace
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoFinalDesarrollo.Models.ClientesModel", b =>
                {
                    b.Property<int>("CodigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<int>("CategoriaCliente")
                        .HasColumnType("Int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("Varchar(25)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.HasKey("CodigoCliente");

                    b.ToTable("tbl_ClientesModel");
                });

            modelBuilder.Entity("ProyectoFinalDesarrollo.Models.DVentaModel", b =>
                {
                    b.Property<int>("CodigoDVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("Int");

                    b.Property<int>("CodigoEVenta")
                        .HasColumnType("Int");

                    b.Property<int>("CodigoProducto")
                        .HasColumnType("Int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("Decimal");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("Decimal");

                    b.HasKey("CodigoDVenta");

                    b.ToTable("tbl_DVentaModel");
                });

            modelBuilder.Entity("ProyectoFinalDesarrollo.Models.EVentaModel", b =>
                {
                    b.Property<int>("CodigoEVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("Int");

                    b.Property<int>("Estado")
                        .HasColumnType("Int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("Date");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("Int");

                    b.HasKey("CodigoEVenta");

                    b.ToTable("tbl_EVentaModel");
                });

            modelBuilder.Entity("ProyectoFinalDesarrollo.Models.ProductosModel", b =>
                {
                    b.Property<int>("CodigoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoProveedor")
                        .HasColumnType("Int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<int>("ExistenciaMinima")
                        .HasColumnType("Int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("Date");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("Decimal");

                    b.Property<int>("TipoProducto")
                        .HasColumnType("Int");

                    b.Property<string>("UbicacionFisica")
                        .IsRequired()
                        .HasColumnType("Varchar(25)");

                    b.HasKey("CodigoProducto");

                    b.ToTable("tbl_ProductosModel");
                });
#pragma warning restore 612, 618
        }
    }
}
